In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings('ignore')
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
import pickle
from sklearn.model_selection import cross_val_score

In [2]:
df=pd.read_csv('ibm.csv')

In [3]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [12]:
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [5]:
df.corr()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
Age,1.000000,0.010661,-0.001686,0.208034,NaN,-0.010145,0.010146,0.024287,0.029820,0.509604,...,0.053535,NaN,0.037510,0.680381,-0.019621,-0.021490,0.311309,0.212901,0.216513,0.202089
DailyRate,0.010661,1.000000,-0.004985,-0.016806,NaN,-0.050990,0.018355,0.023381,0.046135,0.002966,...,0.007846,NaN,0.042143,0.014515,0.002453,-0.037848,-0.034055,0.009932,-0.033229,-0.026363
DistanceFromHome,-0.001686,-0.004985,1.000000,0.021042,NaN,0.032916,-0.016075,0.031131,0.008783,0.005303,...,0.006557,NaN,0.044872,0.004628,-0.036942,-0.026556,0.009508,0.018845,0.010029,0.014406
Education,0.208034,-0.016806,0.021042,1.000000,NaN,0.042070,-0.027128,0.016775,0.042438,0.101589,...,-0.009118,NaN,0.018422,0.148280,-0.025100,0.009819,0.069114,0.060236,0.054254,0.069065
EmployeeCount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EmployeeNumber,-0.010145,-0.050990,0.032916,0.042070,NaN,1.000000,0.017621,0.035179,-0.006888,-0.018519,...,-0.069861,NaN,0.062227,-0.014365,0.023603,0.010309,-0.011240,-0.008416,-0.009019,-0.009197
EnvironmentSatisfaction,0.010146,0.018355,-0.016075,-0.027128,NaN,0.017621,1.000000,-0.049857,-0.008278,0.001212,...,0.007665,NaN,0.003432,-0.002693,-0.019359,0.027627,0.001458,0.018007,0.016194,-0.004999
HourlyRate,0.024287,0.023381,0.031131,0.016775,NaN,0.035179,-0.049857,1.000000,0.042861,-0.027853,...,0.001330,NaN,0.050263,-0.002334,-0.008548,-0.004607,-0.019582,-0.024106,-0.026716,-0.020123
JobInvolvement,0.029820,0.046135,0.008783,0.042438,NaN,-0.006888,-0.008278,0.042861,1.000000,-0.012630,...,0.034297,NaN,0.021523,-0.005533,-0.015338,-0.014617,-0.021355,0.008717,-0.024184,0.025976
JobLevel,0.509604,0.002966,0.005303,0.101589,NaN,-0.018519,0.001212,-0.027853,-0.012630,1.000000,...,0.021642,NaN,0.013984,0.782208,-0.018191,0.037818,0.534739,0.389447,0.353885,0.375281
JobSatisfaction,-0.004892,0.030571,-0.003669,-0.011296,NaN,-0.046247,-0.006784,-0.071335,-0.021476,-0.001944,...,-0.012454,NaN,0.010690,-0.020185,-0.005779,-0.019459,-0.003803,-0.002305,-0.018214,-0.027656
MonthlyIncome,0.497855,0.007707,-0.017014,0.094961,NaN,-0.014829,-0.006259,-0.015794,-0.015271,0.950300,...,0.025873,NaN,0.005408,0.772893,-0.021736,0.030683,0.514285,0.363818,0.344978,0.344079
MonthlyRate,0.028051,-0.032182,0.027473,-0.026084,NaN,0.012648,0.037600,-0.015297,-0.016322,0.039563,...,-0.004085,NaN,-0.034323,0.026442,0.001467,0.007963,-0.023655,-0.012815,0.001567,-0.036746
NumCompaniesWorked,0.299635,0.038153,-0.029251,0.126317,NaN,-0.001251,0.012594,0.022157,0.015012,0.142501,...,0.052733,NaN,0.030075,0.237639,-0.066054,-0.008366,-0.118421,-0.090754,-0.036814,-0.110319
PercentSalaryHike,0.003634,0.022704,0.040235,-0.011111,NaN,-0.012944,-0.031701,-0.009062,-0.017205,-0.034730,...,-0.040490,NaN,0.007528,-0.020608,-0.005221,-0.003280,-0.035991,-0.001520,-0.022154,-0.011985
PerformanceRating,0.001904,0.000473,0.027110,-0.024539,NaN,-0.020359,-0.029548,-0.002172,-0.029071,-0.021222,...,-0.031351,NaN,0.003506,0.006744,-0.015579,0.002572,0.003435,0.034986,0.017896,0.022827
RelationshipSatisfaction,0.053535,0.007846,0.006557,-0.009118,NaN,-0.069861,0.007665,0.001330,0.034297,0.021642,...,1.000000,NaN,-0.045952,0.024054,0.002497,0.019604,0.019367,-0.015123,0.033493,-0.000867
StandardHours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockOptionLevel,0.037510,0.042143,0.044872,0.018422,NaN,0.062227,0.003432,0.050263,0.021523,0.013984,...,-0.045952,NaN,1.000000,0.010136,0.011274,0.004129,0.015058,0.050818,0.014352,0.024698
TotalWorkingYears,0.680381,0.014515,0.004628,0.148280,NaN,-0.014365,-0.002693,-0.002334,-0.005533,0.782208,...,0.024054,NaN,0.010136,1.000000,-0.035662,0.001008,0.628133,0.460365,0.404858,0.459188
TrainingTimesLastYear,-0.019621,0.002453,-0.036942,-0.025100,NaN,0.023603,-0.019359,-0.008548,-0.015338,-0.018191,...,0.002497,NaN,0.011274,-0.035662,1.000000,0.028072,0.003569,-0.005738,-0.002067,-0.004096
WorkLifeBalance,-0.021490,-0.037848,-0.026556,0.009819,NaN,0.010309,0.027627,-0.004607,-0.014617,0.037818,...,0.019604,NaN,0.004129,0.001008,0.028072,1.000000,0.012089,0.049856,0.008941,0.002759
YearsAtCompany,0.311309,-0.034055,0.009508,0.069114,NaN,-0.011240,0.001458,-0.019582,-0.021355,0.534739,...,0.019367,NaN,0.015058,0.628133,0.003569,0.012089,1.000000,0.758754,0.618409,0.769212
YearsInCurrentRole,0.212901,0.009932,0.018845,0.060236,NaN,-0.008416,0.018007,-0.024106,0.008717,0.389447,...,-0.015123,NaN,0.050818,0.460365,-0.005738,0.049856,0.758754,1.000000,0.548056,0.714365
YearsSinceLastPromotion,0.216513,-0.033229,0.010029,0.054254,NaN,-0.009019,0.016194,-0.026716,-0.024184,0.353885,...,0.033493,NaN,0.014352,0.404858,-0.002067,0.008941,0.618409,0.548056,1.000000,0.510224
YearsWithCurrManager,0.202089,-0.026363,0.014406,0.069065,NaN,-0.009197,-0.004999,-0.020123,0.025976,0.375281,...,-0.000867,NaN,0.024698,0.459188,-0.004096,0.002759,0.769212,0.714365,0.510224,1.000000

In [11]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [8]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le=LabelEncoder()

In [19]:
col_t=['Attrition','BusinessTravel','Department','DistanceFromHome','Education','EducationField','Gender','JobRole','MaritalStatus','Over18','OverTime']

In [20]:
for m in col_t:
    df[m]=le.fit_transform(df[m])

In [21]:
df.dtypes

Age                         int64
Attrition                   int64
BusinessTravel              int64
DailyRate                   int64
Department                  int64
DistanceFromHome            int64
Education                   int64
EducationField              int64
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                      int64
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                     int32
JobSatisfaction             int64
MaritalStatus               int32
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                      int32
OverTime                    int32
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [115]:
y=df.iloc[:,1]

In [116]:
df_x=df.drop('Attrition',axis=1)

In [150]:
x=df_x.iloc[:,0:34]

In [118]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y)

In [119]:
lr=LogisticRegression()

In [120]:
lr.fit(xtrain,ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [121]:
lr.score(xtrain,ytrain)

0.8802177858439202

In [122]:
pred_lr=lr.predict(xtest)

In [123]:
accuracy_score(pred_lr,ytest)

0.8722826086956522

In [124]:
confusion_matrix(pred_lr,ytest)

array([[299,  37],
       [ 10,  22]], dtype=int64)

In [125]:
print(classification_report(pred_lr,ytest))

              precision    recall  f1-score   support

           0       0.97      0.89      0.93       336
           1       0.37      0.69      0.48        32

    accuracy                           0.87       368
   macro avg       0.67      0.79      0.71       368
weighted avg       0.92      0.87      0.89       368

In [126]:
rfr=RandomForestClassifier()

In [127]:
rfr.fit(xtrain,ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [128]:
rfr.score(xtrain,ytrain)

0.9782214156079855

In [129]:
pred_r=rfr.predict(xtest)

In [130]:
accuracy_score(pred_r,ytest)

0.8559782608695652

In [131]:
cv=cross_val_score(lr,x,y,cv=15)

In [132]:
cv.mean()

0.8707293143228342

In [133]:
cv.std()

0.02101090946266557

In [134]:
rfr.feature_importances_

array([0.064192  , 0.01099474, 0.06885668, 0.01114328, 0.04283882,
       0.01749516, 0.02397394, 0.        , 0.04179081, 0.02015879,
       0.00882193, 0.05916192, 0.02852651, 0.03289521, 0.02123063,
       0.02504824, 0.01407629, 0.06819099, 0.04460991, 0.03177747,
       0.        , 0.04054933, 0.03670336, 0.00495788, 0.02727445,
       0.        , 0.03298405, 0.04961879, 0.02418043, 0.02018635,
       0.04186247, 0.02650299, 0.03426249, 0.02513407])

In [135]:
ada=AdaBoostClassifier(base_estimator=rfr,n_estimators=100)

In [136]:
ada.fit(xtrain,ytrain)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         n_estimators=10,
                                                         n_jobs=None,
                                                         oob_score=False,
                                                         random_state=None,
                                                         verbose=0,
                                                         warm_start=False),
                   learning_rate=1.0, n_estimators=100, random_state=None)

In [137]:
ada.score(xtrain,ytrain)

1.0

In [138]:
adar=ada.predict(xtest)

In [139]:
accuracy_score(adar,ytest)

0.8532608695652174

In [140]:
cvr=cross_val_score(ada,x,y,cv=20,scoring='accuracy')

In [141]:
cvr.mean()

0.8551578119215104

In [142]:
cvr.std()

0.01692102614768741

In [143]:
imp=rfr.feature_importances_

In [144]:
feature=x.columns

In [145]:
important=pd.DataFrame({'imp':imp,'feature':feature})

In [146]:
important.sort_values('imp')

         imp                   feature
7   0.000000             EmployeeCount
25  0.000000             StandardHours
20  0.000000                    Over18
23  0.004958         PerformanceRating
10  0.008822                    Gender
1   0.010995            BusinessTravel
3   0.011143                Department
16  0.014076             MaritalStatus
5   0.017495                 Education
9   0.020159   EnvironmentSatisfaction
29  0.020186           WorkLifeBalance
14  0.021231                   JobRole
6   0.023974            EducationField
28  0.024180     TrainingTimesLastYear
15  0.025048           JobSatisfaction
33  0.025134      YearsWithCurrManager
31  0.026503        YearsInCurrentRole
24  0.027274  RelationshipSatisfaction
12  0.028527            JobInvolvement
19  0.031777        NumCompaniesWorked
13  0.032895                  JobLevel
26  0.032984          StockOptionLevel
32  0.034262   YearsSinceLastPromotion
22  0.036703         PercentSalaryHike
21  0.040549                  OverTime
8   0.041791            EmployeeNumber
30  0.041862            YearsAtCompany
4   0.042839          DistanceFromHome
18  0.044610               MonthlyRate
27  0.049619         TotalWorkingYears
11  0.059162                HourlyRate
0   0.064192                       Age
17  0.068191             MonthlyIncome
2   0.068857                 DailyRate

In [147]:
cols_drop=['EmployeeCount','Over18','StandardHours','Gender','Department','PerformanceRating','BusinessTravel','RelationshipSatisfaction','JobInvolvement','WorkLifeBalance','Education','EducationField']

In [148]:
df_drop=df.drop(cols_drop,axis=1)

In [151]:
x_drop=df_drop

In [153]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(x_drop,y)

In [154]:
lr.fit(Xtrain,Ytrain)
lr.score(Xtrain,Ytrain)
pred_drop=lr.predict(Xtest)

In [155]:
accuracy_score(pred_drop,Ytest)

1.0

In [171]:
cv_drop=cross_val_score(lr,x,y,cv=20,scoring='accuracy')

In [172]:
cv_drop.mean()

0.865292175737381

In [173]:
cv_drop.std()

0.022338727016480413

In [159]:
rfr.fit(Xtrain,Ytrain)
rfr.score(Xtrain,Ytrain)
pred_droprfr=rfr.predict(Xtest)

In [160]:
accuracy_score(pred_droprfr,Ytest)

1.0

In [161]:
confusion_matrix(pred_droprfr,Ytest)

array([[310,   0],
       [  0,  58]], dtype=int64)

In [162]:
print(classification_report(pred_droprfr,Ytest))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       310
           1       1.00      1.00      1.00        58

    accuracy                           1.00       368
   macro avg       1.00      1.00      1.00       368
weighted avg       1.00      1.00      1.00       368

In [168]:
cvrfr=cross_val_score(rfr,x,y,cv=20,scoring='accuracy')

In [169]:
cvrfr.mean()

0.8504746184540706

In [170]:
cvrfr.std()

0.020211141418858467